# GNU Make project makefile autogenerated by GENie
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(MAKESHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
  RM    = $(SILENT) rm -f "$(1)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || exit 0
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
  RM    = $(SILENT) del /F "$(subst /,\\,$(1))" 2> nul || exit 0
endif

CC  = gcc
CXX = g++
AR  = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

MAKEFILE = flatbuffers.make

ifeq ($(config),debug32)
  OBJDIR              = ../build/x32/debug/flatbuffers
  TARGETDIR           = ../bin/x32_debug/flatbuffers
  TARGET              = $(TARGETDIR)/flatc
  DEFINES            += -DFLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE -DDEBUG -DFTS_OSX
  INCLUDES           += -I../../../code/thirdparty
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -m32
  LDDEPS             +=
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/code/thirdparty/flatbuffers/flatc.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_cpp.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_fbs.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_general.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_text.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_parser.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/util.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR              = ../build/x32/release/flatbuffers
  TARGETDIR           = ../bin/x32_release/flatbuffers
  TARGET              = $(TARGETDIR)/flatc
  DEFINES            += -DFLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE -DNDEBUG -DFTS_OSX
  INCLUDES           += -I../../../code/thirdparty
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m32 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -m32
  LDDEPS             +=
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/code/thirdparty/flatbuffers/flatc.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_cpp.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_fbs.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_general.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_text.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_parser.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/util.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR              = ../build/x64/debug/flatbuffers
  TARGETDIR           = ../bin/x64_debug/flatbuffers
  TARGET              = $(TARGETDIR)/flatc
  DEFINES            += -DFLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE -DDEBUG -DFTS_OSX
  INCLUDES           += -I../../../code/thirdparty
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -m64
  LDDEPS             +=
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/code/thirdparty/flatbuffers/flatc.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_cpp.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_fbs.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_general.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_text.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_parser.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/util.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR              = ../build/x64/release/flatbuffers
  TARGETDIR           = ../bin/x64_release/flatbuffers
  TARGET              = $(TARGETDIR)/flatc
  DEFINES            += -DFLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE -DNDEBUG -DFTS_OSX
  INCLUDES           += -I../../../code/thirdparty
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2 -m64 -Wdeprecated-declarations -Wmissing-braces -Wunused-local-typedef
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -m64
  LDDEPS             +=
  LIBS               += $(LDDEPS)
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/code/thirdparty/flatbuffers/flatc.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_cpp.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_fbs.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_general.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_text.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/idl_parser.o \
	$(OBJDIR)/code/thirdparty/flatbuffers/util.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJDIRS := \
	$(OBJDIR) \
	$(OBJDIR)/code/thirdparty/flatbuffers \

RESOURCES := \

.PHONY: clean prebuild prelink

all: $(OBJDIRS) prebuild prelink $(TARGET) | $(TARGETDIR)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(EXTERNAL_LIBS) $(RESOURCES) | $(TARGETDIR) $(OBJDIRS)
	@echo Linking flatbuffers
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	-$(call MKDIR,$(TARGETDIR))

$(OBJDIRS):
	@echo Creating $(@)
	-$(call MKDIR,$@)

clean:
	@echo Cleaning flatbuffers
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) -x c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"

$(GCH_OBJC): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_OBJCPPFLAGS) -x objective-c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"
endif

$(OBJDIR)/code/thirdparty/flatbuffers/flatc.o: ../../../code/thirdparty/flatbuffers/flatc.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_cpp.o: ../../../code/thirdparty/flatbuffers/idl_gen_cpp.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_fbs.o: ../../../code/thirdparty/flatbuffers/idl_gen_fbs.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_general.o: ../../../code/thirdparty/flatbuffers/idl_gen_general.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/code/thirdparty/flatbuffers/idl_gen_text.o: ../../../code/thirdparty/flatbuffers/idl_gen_text.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/code/thirdparty/flatbuffers/idl_parser.o: ../../../code/thirdparty/flatbuffers/idl_parser.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/code/thirdparty/flatbuffers/util.o: ../../../code/thirdparty/flatbuffers/util.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
  -include $(OBJDIR)/$(notdir $(PCH))_objc.d
endif
